
name: New Pull Request Chime Notification

on:
  pull_request:
    branches: [ master ]
    types: opened
    
jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
      - name: New Pull Request
        uses: aws-actions/amazon-chime-github-webhook@v1
        with:
          webhook: ${{secrets.NEW_PULL_REQUEST}}
          message: New Pull Request by ${{ github.actor }} - [${{ github.event.pull_request.title }}](${{github.event.pull_request.html_url}})
